# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{delicious-cli}
  s.version = "0.4.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{epitron}]
  s.date = %q{2011-09-29}
  s.description = %q{A commandline tool which lets you download all your delicious.com links and search them (with pretty color-coded results).}
  s.email = %q{chris@ill-logic.com}
  s.executables = [%q{delicious}, %q{dels}]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "lib/delicious-cli.rb",
    "lib/delicious-cli/api.rb",
    "lib/delicious-cli/blank.rb",
    "lib/delicious-cli/colored.rb",
    "lib/delicious-cli/db.rb",
    "lib/delicious-cli/display.rb",
    "lib/delicious-cli/log.rb",
    "lib/delicious-cli/settings.rb"
  ]
  s.homepage = %q{http://github.com/epitron/delicious-cli}
  s.post_install_message = %q{
========================================================================
Delicious-CLI installed!
------------------------------------------------------------------------

To configure your Delicious.com account, type:

  $ dels
  
To search, type:

  $ dels <search term(s)>

To pull new links from your delicious account, type:

  $ dels -s
  
To add dels -s to your crontab, type:

  $ crontab -e
  
That's all, folks!
  
========================================================================
}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Delicious.com commandline interface}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
  end
end

